server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

  rabbitmq:
    host: localhost
    port: 5672
    username: ani
    password: mypassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: false # Not using relational DB, disable unnecessary check
    mongo:
      enabled: true  # Enable MongoDB health check
    rabbit:
      enabled: true  # Enable RabbitMQ health check

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


user:
  service:
    url: http://user-service  # Eureka LoadBalancer will resolve USER-SERVICE

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
