server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: root
    password: "@ani.8727M"

  jpa:
    hibernate:
      ddl-auto: update           # Good for dev, but consider 'validate' or migrations (Flyway/Liquibase) for production
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

