spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   # ❗ Do not register the Eureka server as a client
    fetch-registry: false         # ❗ This is the registry itself, no need to fetch others

  server:
    enable-self-preservation: false   # ✅ Disable self-preservation for dev, shows dead instances quickly
    eviction-interval-timer-in-ms: 5000  # Optional: evict dead instances every 5 seconds (default 60 sec)

management:
  endpoints:
    web:
      exposure:
        include: health,info  # Expose health/info endpoints for easy monitoring
